openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Pets"
        default:
          $ref: 'responses/unexpected_error.yaml'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      requestBody:
        $ref: 'requestBodies/pet.yaml'
      responses:
        '201':
          description: Null response
        default:
          $ref: 'responses/unexpected_error.yaml'
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - $ref: 'parameters.yaml#/queryPetId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Pet"
        default:
          $ref: 'responses/unexpected_error.yaml'

    put:
      summary: Edit a pet
      tags:
        - pets
      parameters:
        - $ref: 'parameters.yaml#/queryPetId'
      requestBody:
        $ref: 'requestBodies/pet.yaml'
      responses:
        '201':
          description: Null response
        default:
          $ref: 'responses/unexpected_error.yaml'
